# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

# gem "rails"
gem 'tty-prompt', '~> 0.23.1'
gem 'colorize', '~> 0.8.1'
gem 'tty-progressbar'
gem 'tty-cursor', '~> 0.7.1'
gem 'tty-screen', '~> 0.8.1'
gem 'rspec'
gem 'tty-font', '~> 0.2.0'
gem 'rake', '~> 13.0', '>= 13.0.6'